import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/out/**',
      'apps/mobile/**',
      'eval/out/**',
      'Doc/**',
      // Generated by Next on every build; not ours to lint.
      'apps/web/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
      // The orchestrator handles untrusted provider payloads; explicit narrowing
      // is required rather than silently trusting `any`.
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
);
