import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/out/**',
      'apps/mobile/**',
      'eval/out/**',
      'Doc/**',
      // Generated by Next on every build; not ours to lint.
      'apps/web/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
      // The orchestrator handles untrusted provider payloads; explicit narrowing
      // is required rather than silently trusting `any`.
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  {
    // Build-time helper scripts run under Node as CommonJS, so `require`,
    // `process` and `console` are legitimate there. Without this they are
    // linted against the app's browser/ESM assumptions and every one of them
    // is reported as an undefined global.
    files: ['scripts/**/*.js', '**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        require: 'readonly',
        module: 'writable',
        process: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        Buffer: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
);
