'use client';

/**
 * A negotiation transcript that reveals itself the way it happened, instead
 * of dumping the whole exchange at once — history renders instantly (no
 * replaying a deal that already closed every time the page loads), but a
 * message that just arrived from Firestore gets a short "composing" hold and
 * then types itself out, character by character. This is the operations
 * console's version of the same beat apps/web/src/components/landing/negotiation.tsx
 * scripts for the marketing page — except the data underneath it is real:
 * generated by services/orchestrator/src/negotiate-llm.ts, not a fixed
 * script.
 */

import dynamic from 'next/dynamic';
import { useEffect, useRef, useState } from 'react';
import { Marker, type Tone } from '@/components/primitives';
import { THINKING_LOTTIE } from '@/components/landing/thinking';
import type { AgentMessage } from '@/components/live';

const Lottie = dynamic(() => import('lottie-react'), { ssr: false });

const KIND_TONE: Record<string, Tone> = {
  proposal: 'neutral',
  counter: 'hazard',
  accept: 'clear',
  reject: 'refused',
  note: 'neutral',
};

const COMPOSE_HOLD_MS = 550;
const MS_PER_CHAR = 16;

export function NegotiationThread({
  threadKey,
  messages,
}: {
  /** Changes whenever the selected negotiation changes, so the animation state resets cleanly. */
  readonly threadKey: string;
  readonly messages: readonly AgentMessage[];
}) {
  const seenIds = useRef<Set<string>>(new Set());
  const knownThread = useRef<string | null>(null);
  const reducedMotion = useRef(false);
  const timers = useRef<{ compose?: ReturnType<typeof setTimeout>; type?: ReturnType<typeof setInterval> }>({});
  const processing = useRef(false);

  const [settled, setSettled] = useState<readonly AgentMessage[]>([]);
  const [queue, setQueue] = useState<readonly AgentMessage[]>([]);
  const [composing, setComposing] = useState(false);
  const [typed, setTyped] = useState('');

  useEffect(() => {
    reducedMotion.current = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  }, []);

  // New thread selected: show its existing history instantly (this is a
  // re-read, not a live arrival) and reset all animation state. Otherwise,
  // queue only the messages not already seen for this thread.
  useEffect(() => {
    if (knownThread.current !== threadKey) {
      knownThread.current = threadKey;
      seenIds.current = new Set(messages.map((message) => message.id));
      setSettled(messages);
      setQueue([]);
      setComposing(false);
      setTyped('');
      return;
    }
    const fresh = messages.filter((message) => !seenIds.current.has(message.id));
    if (fresh.length === 0) return;
    for (const message of fresh) seenIds.current.add(message.id);
    setQueue((current) => [...current, ...fresh]);
  }, [threadKey, messages]);

  useEffect(() => {
    if (processing.current || queue.length === 0) return;
    const [next, ...rest] = queue;
    if (!next) return;
    processing.current = true;

    if (reducedMotion.current) {
      setSettled((current) => [...current, next]);
      setQueue(rest);
      processing.current = false;
      return;
    }

    setComposing(true);
    setTyped('');
    timers.current.compose = setTimeout(() => {
      setComposing(false);
      let shown = 0;
      timers.current.type = setInterval(() => {
        shown += 1;
        setTyped(next.text.slice(0, shown));
        if (shown >= next.text.length) {
          clearInterval(timers.current.type);
          setSettled((current) => [...current, next]);
          setQueue(rest);
          setTyped('');
          processing.current = false;
        }
      }, MS_PER_CHAR);
    }, COMPOSE_HOLD_MS);

    return () => {
      if (timers.current.compose) clearTimeout(timers.current.compose);
      if (timers.current.type) clearInterval(timers.current.type);
    };
    // Deliberately [queue] only: `next`/`rest` are derived from it each run,
    // and this repo has no react-hooks lint plugin registered to ask for more.
  }, [queue]);

  const pending = queue[0];

  return (
    <ul className="space-y-3 p-4">
      {settled.map((message) => (
        <li key={message.id} className="border-l-2 border-[var(--color-seam)] py-1 pl-4">
          <div className="flex items-center gap-2">
            <Marker tone={KIND_TONE[message.kind ?? 'note'] ?? 'neutral'}>{message.kind ?? 'note'}</Marker>
            <span className="eyebrow">{message.from}</span>
          </div>
          <p className="mt-1.5 text-sm text-[var(--color-chalk-soft)]">{message.text}</p>
        </li>
      ))}

      {pending ? (
        <li className="arriving border-l-2 border-[var(--color-hazard)] py-1 pl-4">
          <div className="flex items-center gap-2">
            <Marker tone={KIND_TONE[pending.kind ?? 'note'] ?? 'neutral'}>{pending.kind ?? 'note'}</Marker>
            <span className="eyebrow">{pending.from}</span>
            {composing ? (
              <span className="flex items-center gap-1.5">
                <span className="h-4 w-4">
                  <Lottie animationData={THINKING_LOTTIE} loop autoplay />
                </span>
                <span className="eyebrow">composing…</span>
              </span>
            ) : null}
          </div>
          {!composing ? (
            <p className="mt-1.5 text-sm text-[var(--color-chalk-soft)]">
              {typed}
              <span aria-hidden className="animate-pulse">
                ▌
              </span>
            </p>
          ) : null}
        </li>
      ) : null}
    </ul>
  );
}
