/**
 * A real negotiation, generated by an LLM — buyer persona vs. seller
 * persona, several turns, and the model decides where the deal lands.
 *
 * eval/src/executor.ts's guardedExecutor still runs first (offer discovery,
 * injection screening — untouched, still the tested deterministic reference)
 * and computes its own 6%-concession price as it always has. This module
 * only runs afterward, in the live orchestrator, and *replaces* that price
 * with whatever the model actually negotiates. The deterministic figure
 * guardedExecutor already put in `world.agreedPrice` becomes the fallback:
 * if the model call fails, times out, produces a garbled/leaked-instruction
 * reply, or its closing line has no parseable positive number, that figure
 * is what's used instead — an integrity guard against garbage input, not a
 * ceiling on a legitimate negotiated outcome. Downstream, the budget
 * engine's workflow/step/approval caps (packages/core/src/policy/budget.ts)
 * apply to whatever price arrives here exactly as they do to every other
 * price source; nothing here bypasses them.
 *
 * Small local models (this repo's default is qwen2.5:0.5b — ~350MB, chosen
 * for demo speed over quality) don't reliably separate "instructions" from
 * "the line I'm supposed to say": in testing, a meaningful fraction of
 * replies echoed fragments of the system prompt back verbatim instead of
 * writing dialogue. Rather than accept that in the UI, `looksLikeLeak` below
 * treats it as a failure and falls back — the same integrity guard as an
 * unparseable price, applied to every turn, not just the last one.
 */

import { formatMoney, parseAmount, type AssetCode, type CompiledStep, type Money } from '@logisticdigi/core';
import type { Offer } from '@logisticdigi/sim';
import type { World } from '@logisticdigi/eval';
import { negotiationDocsFrom } from './mirror.js';
import type { LlmClient, LlmMessage } from './llm/client.js';
import type { MessageDoc, NegotiationDoc } from './store.js';

/** The Negotiation agent's real permission/restriction pair — the same text apps/web/src/components/agent-rail.tsx shows an operator. */
const NEGOTIATION_AGENT = {
  permission: 'Bargain with counterparty bots.',
  restriction: 'Cannot agree above target price.',
} as const;

export interface NegotiateInput {
  readonly tenantId: string;
  readonly runId: string;
  readonly at: number;
}

export interface NegotiateResult {
  readonly agreedPrice: Money;
  readonly negotiation: NegotiationDoc;
  readonly messages: readonly MessageDoc[];
}

const TURN_KINDS: readonly MessageDoc['kind'][] = ['proposal', 'counter', 'counter', 'accept'];
const MAX_REPLY_CHARS = 200;
const FINAL_PRICE_LINE = /FINAL_PRICE:\s*([0-9]+(?:\.[0-9]+)?)/i;

/** Phrases that only exist in *our own instructions* — a reply containing one didn't write dialogue, it echoed the prompt. */
const LEAK_MARKERS = [
  'final_price',
  'plain decimal number',
  'no currency symbol',
  'no extra words',
  'write one short line',
  'stay in character',
  'staying in character',
  'you are the negotiation agent',
  'you are negotiating',
];

function clip(text: string): string {
  return text
    .trim()
    .replace(/\s+/g, ' ')
    .replace(/^["'“”]+|["'“”]+$/g, '')
    .slice(0, MAX_REPLY_CHARS);
}

function looksLikeLeak(text: string): boolean {
  if (text.length < 3) return true;
  const lower = text.toLowerCase();
  return LEAK_MARKERS.some((marker) => lower.includes(marker));
}

function extractFinalPrice(text: string, asset: AssetCode): Money | null {
  const match = FINAL_PRICE_LINE.exec(text);
  if (!match?.[1]) return null;
  try {
    const amount = parseAmount(asset, match[1]);
    return amount.units > 0n ? amount : null;
  } catch {
    return null;
  }
}

/** Strips the FINAL_PRICE line (and anything after it) before the closing line is shown as dialogue. */
function stripFinalPriceLine(text: string): string {
  const cut = text.search(FINAL_PRICE_LINE);
  return clip(cut === -1 ? text : text.slice(0, cut));
}

function buyerSystemPrompt(offer: Offer, target: Money | undefined): LlmMessage {
  return {
    role: 'system',
    content:
      `You are a freight-procurement negotiator buying from ${offer.providerName}. ` +
      `Permission: ${NEGOTIATION_AGENT.permission} Restriction: ${NEGOTIATION_AGENT.restriction}` +
      (target ? ` Do not exceed ${formatMoney(target)}.` : '') +
      ` Item: "${offer.title}", opening price ${formatMoney(offer.price)}. ` +
      `Reply with only the one line you would say out loud next — no notes, no stage directions, no quotes around it.`,
  };
}

function sellerSystemPrompt(offer: Offer): LlmMessage {
  return {
    role: 'system',
    content:
      `You are ${offer.providerName}, selling "${offer.title}" for ${formatMoney(offer.price)}. ` +
      `You want a good price but will move to close the deal. ` +
      `Reply with only the one line you would say out loud next — no notes, no stage directions, no quotes around it.`,
  };
}

function fallback(step: CompiledStep, offer: Offer, world: World, input: NegotiateInput): NegotiateResult {
  const price = world.agreedPrice ?? offer.price;
  const { negotiation, messages } = negotiationDocsFrom(step, offer, price, input);
  return { agreedPrice: price, negotiation, messages };
}

async function say(client: LlmClient, system: LlmMessage, user: string): Promise<string> {
  const reply = clip(await client.complete([system, { role: 'user', content: user }]));
  if (looksLikeLeak(reply)) throw new Error(`reply looked like a leaked instruction, not dialogue: "${reply}"`);
  return reply;
}

export async function negotiateWithLlm(
  step: CompiledStep,
  offer: Offer,
  world: World,
  client: LlmClient,
  input: NegotiateInput,
): Promise<NegotiateResult> {
  const negotiationId = `${input.runId}:${step.id}`;
  const buyerSystem = buyerSystemPrompt(offer, step.maxSpend);
  const sellerSystem = sellerSystemPrompt(offer);

  try {
    const turns: { readonly speaker: 'buyer' | 'seller'; readonly text: string }[] = [];

    const opening = await say(client, sellerSystem, 'Open the negotiation with your offer, in one line.');
    turns.push({ speaker: 'seller', text: opening });

    const counter = await say(
      client,
      buyerSystem,
      `${offer.providerName} said: ${opening} Reply with your counter-offer, in one line.`,
    );
    turns.push({ speaker: 'buyer', text: counter });

    const push = await say(
      client,
      sellerSystem,
      `The buyer said: ${counter} Reply — move closer to a deal, or hold firm this one time. One line.`,
    );
    turns.push({ speaker: 'seller', text: push });

    // The FINAL_PRICE instruction lives only in this one user turn, not the
    // persistent system prompt — it is asked for exactly once, right before
    // it is needed, which is what keeps a weak model from parroting it back
    // on earlier turns.
    const closingRaw = clip(
      await client.complete([
        buyerSystem,
        {
          role: 'user',
          content:
            `${offer.providerName} said: ${push} This is your final turn: write one closing line, then on a ` +
            `new line write exactly: FINAL_PRICE: <number> (a plain number in ${offer.price.asset}).`,
        },
      ]),
    );
    const agreedPrice = extractFinalPrice(closingRaw, offer.price.asset);
    if (!agreedPrice) throw new Error('closing line had no parseable FINAL_PRICE');
    const stripped = stripFinalPriceLine(closingRaw);
    // A small model asked for a closing line *and* a FINAL_PRICE line often
    // only manages the second — "FINAL_PRICE: 214.50" with nothing before
    // it. That is a real, honest price decision with no dialogue attached,
    // not a leaked instruction; give it a plain confirmation line rather
    // than discarding a perfectly good negotiated price over formatting.
    const closingLine =
      stripped.length === 0 ? `Agreed — ${formatMoney(agreedPrice)}.` : stripped;
    if (looksLikeLeak(closingLine)) throw new Error(`closing line looked like a leaked instruction: "${closingLine}"`);
    turns.push({ speaker: 'buyer', text: closingLine });

    const messages: MessageDoc[] = turns.map((turn, i) => ({
      id: `${negotiationId}:${i + 1}`,
      from: turn.speaker === 'buyer' ? input.tenantId : offer.providerId,
      fromRole: turn.speaker === 'buyer' ? 'negotiation' : 'counterparty',
      to: turn.speaker === 'buyer' ? offer.providerId : input.tenantId,
      text: turn.text,
      sentAt: input.at + i,
      kind: TURN_KINDS[i] ?? 'note',
    }));

    return {
      agreedPrice,
      negotiation: {
        id: negotiationId,
        buyerTenantId: input.tenantId,
        sellerTenantId: offer.providerId,
        sellerName: offer.providerName,
        runId: input.runId,
        title: offer.title,
        startedAt: input.at,
      },
      messages,
    };
  } catch (cause) {
    console.warn(`[negotiate-llm] falling back to the deterministic concession: ${(cause as Error).message}`);
    return fallback(step, offer, world, input);
  }
}
